### ISSUE TITLE
App getting crashed on iPad

### ISSUE THREAD

**Issue by ilabsbalaji** [smilefam/SendBird-Unity#2]
I installed this demo app into my iPad.  Started the Group channel, and invited the user to chat. Now me app is in Chat mode. Now I locked my iPad. After 10 seconds I unlocked my iPad. The app is crashed. In code I got the below logs.

`**2016-11-25 19:08:29.619446 unitysdk[2193:442383] [DYMTLInitPlatform] platform initialization successful

2016-11-25 19:08:29.750127 unitysdk[2193:442257] -> registered mono modules 0xcf6f50
-> applicationDidFinishLaunching()
2016-11-25 19:08:30.764308 unitysdk[2193:442257] Metal GPU Frame Capture Enabled
2016-11-25 19:08:30.765141 unitysdk[2193:442257] Metal API Validation Enabled
-> applicationDidBecomeActive()
Renderer: PowerVR SGX 554
Vendor:   Imagination Technologies
Version:  OpenGL ES 2.0 IMGSGX554-127
GLES:     2
GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_comp
ression_pvrtc 
OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 349889984
Initialize engine version: 5.4.1f1 (649f48bbbf0f)
-------- Shader compilation failed
#version 100
#extension GL_EXT_frag_depth : enable
precision highp float;
uniform highp vec4 _ProjectionParams;
uniform highp vec4 _ZBufferParams;
uniform highp mat4 unity_CameraToWorld;
uniform highp mat4 _NonJitteredVP;
uniform highp mat4 _PreviousVP;
uniform highp sampler2D _CameraDepthTexture;
varying highp vec2 xlv_TEXCOORD0;
varying highp vec3 xlv_TEXCOORD1;
void main ()
{
  highp vec4 tmpvar_1;
  tmpvar_1 = texture2D (_CameraDepthTexture, xlv_TEXCOORD0);
  mediump vec2 tmpvar_2;
  highp vec4 tmpvar_3;
  tmpvar_3.w = 1.0;
  tmpvar_3.xyz = ((xlv_TEXCOORD1 * (_ProjectionParams.z / xlv_TEXCOORD1.z)) * (1.0/((
    (_ZBufferParams.x * tmpvar_1.x)
   + _ZBufferParams.y))));
  highp vec4 tmpvar_4;
  tmpvar_4 = (unity_CameraToWorld * tmpvar_3);
  highp vec4 tmpvar_5;
  tmpvar_5 = (_PreviousVP * tmpvar_4);
  highp vec4 tmpvar_6;
  tmpvar_6 = (_NonJitteredVP * tmpvar_4);
  highp vec2 tmpvar_7;
  tmpvar_7 = (((tmpvar_5.xy / tmpvar_5.w) + 1.0) / 2.0);
  highp vec2 tmpvar_8;
  tmpvar_8 = (((tmpvar_6.xy / tmpvar_6.w) + 1.0) / 2.0);
  tmpvar_2 = (tmpvar_8 - tmpvar_7);
  mediump vec4 tmpvar_9;
  tmpvar_9.zw = vec2(0.0, 1.0);
  tmpvar_9.xy = tmpvar_2;
  gl_FragDepthEXT = tmpvar_1.x;
  gl_FragData[0] = tmpvar_9;
}
-------- failed compiling:
fragment evaluation shader
WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.
UnloadTime: 5.201916 ms
Setting up 1 worker threads for Enlighten.
  Thread -> id: 402bd000 -> priority: 1 
2016-11-25 19:10:19.631910 unitysdk[2193:442257] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-11-25 19:10:19.633382 unitysdk[2193:442257] [MC] Reading from public effective user settings.
-> applicationWillResignActive()
-> applicationDidEnterBackground()
-> applicationWillEnterForeground()
11/25/2016 19:11:18|Fatal|Logger.output|A null value was found where an object instance was required.
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed
11/25/2016 19:11:18|Error|WSClient.Quit|This operation isn't available in: closed**`

**Comment by sf-harry-kim** [comment]
Sorry for the hassle.

This issue has been fixed with SendBird Unity SDK v3.0.1. I just update the sample with the latest v.3.0.1.

It should work now.
